language: c

jobs:
  include:
    - name: "Xenial clang"
      os: linux
      dist: xenial
      compiler: clang
    - name: "Xenial gcc"
      os: linux
      dist: xenial
      compiler: gcc
    - name: "Bionic clang"
      os: linux
      dist: bionic
      compiler: clang
    - name: "Bionic gcc"
      os: linux
      dist: bionic
      compiler: gcc

script: autoreconf -i -f && ./configure && make
